In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
path = "E:\\Data Science Salarys\\Data\\ds_salaries.csv"
df = pd.read_csv(path, sep=",")

In [3]:
df.head()

,Unnamed: 0,work_year,experience_level,employment_type,job_title,salary,salary_currency,salary_in_usd,employee_residence,remote_ratio,company_location,company_size
0,0,2020,MI,FT,Data Scientist,70000,EUR,79833,DE,0,DE,L
1,1,2020,SE,FT,Machine Learning Scientist,260000,USD,260000,JP,0,JP,S
2,2,2020,SE,FT,Big Data Engineer,85000,GBP,109024,GB,50,GB,M
3,3,2020,MI,FT,Product Data Analyst,20000,USD,20000,HN,0,HN,S
4,4,2020,SE,FT,Machine Learning Engineer,150000,USD,150000,US,50,US,L

In [4]:
df.drop(columns=["Unnamed: 0"], inplace=True)

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 607 entries, 0 to 606
Data columns (total 11 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   work_year           607 non-null    int64
 1   experience_level    607 non-null    str
 2   employment_type     607 non-null    str
 3   job_title           607 non-null    str
 4   salary              607 non-null    int64
 5   salary_currency     607 non-null    str
 6   salary_in_usd       607 non-null    int64
 7   employee_residence  607 non-null    str
 8   remote_ratio        607 non-null    int64
 9   company_location    607 non-null    str
 10  company_size        607 non-null    str
dtypes: int64(4), str(7)
memory usage: 52.3 KB

In [6]:
df['experience_level'] = df['experience_level'].replace({
    'EN': 'Junior',
    'MI': 'Pleno',
    'SE': 'Senior',
    'EX': 'Executive'
})

df['employment_type'] = df['employment_type'].replace({
    'PT': 'Meio período',
    'FT': 'Tempo integral',
    'CT': 'Contrato',
    'FL': 'Freelancer'
})


df['company_size'] = df['company_size'].replace({
    'S': 'Pequena',
    'M': 'Média',
    'L': 'Grande'
})

df['remote_ratio'] = df['remote_ratio'].replace({
    0: 'Presencial',
    50: 'Híbrido',
    100: 'Remoto'
})

df.head()

,work_year,experience_level,employment_type,job_title,salary,salary_currency,salary_in_usd,employee_residence,remote_ratio,company_location,company_size
0,2020,Pleno,Tempo integral,Data Scientist,70000,EUR,79833,DE,Presencial,DE,Grande
1,2020,Senior,Tempo integral,Machine Learning Scientist,260000,USD,260000,JP,Presencial,JP,Pequena
2,2020,Senior,Tempo integral,Big Data Engineer,85000,GBP,109024,GB,Híbrido,GB,Média
3,2020,Pleno,Tempo integral,Product Data Analyst,20000,USD,20000,HN,Presencial,HN,Pequena
4,2020,Senior,Tempo integral,Machine Learning Engineer,150000,USD,150000,US,Híbrido,US,Grande

In [11]:
df['salary'] = df['salary'].astype('float')
df['salary_in_usd'] = df['salary_in_usd'].astype('float')
df['remote_ratio'] = df['remote_ratio'].astype('category')
df['experience_level'] = df['experience_level'].astype('category')
df['employment_type'] = df['employment_type'].astype('category')
df['company_size'] = df['company_size'].astype('category')

In [12]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 607 entries, 0 to 606
Data columns (total 11 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   work_year           607 non-null    int64
 1   experience_level    607 non-null    category
 2   employment_type     607 non-null    category
 3   job_title           607 non-null    str
 4   salary              607 non-null    float64
 5   salary_currency     607 non-null    str
 6   salary_in_usd       607 non-null    float64
 7   employee_residence  607 non-null    str
 8   remote_ratio        607 non-null    category
 9   company_location    607 non-null    str
 10  company_size        607 non-null    category
dtypes: category(4), float64(2), int64(1), str(4)
memory usage: 36.1 KB